### ISSUE TITLE
[feedback] Call fichub_cli directly instead of using subprocess call

### ISSUE THREAD

**Issue by arzkar** [DylanB5402/fic-send-cli#1]
Hi,

I came across your project and it looks like you are using subprocess to call fichub-cli for your needs.
Since your tool is built in Python, another way of doing this could be calling fichub-cli's API directly just like [fichub-cli-metadata](https://github.com/fichub-cli-contrib/fichub-cli-metadata) is doing.
```py
from fichub_cli.utils.fetch_data import FetchData

fic = FetchData(format_type=format_type, out_dir=out_dir, force=force,
                        debug=debug, automated=automated, verbose=verbose)
fic.get_fic_with_url(url)
```
Ref: <https://github.com/FicHub/fichub-cli/blob/af8ecde7db866cf8e672aef2c51104410279088d/fichub_cli/cli.py#L154-L156>

I try to avoid making system calls as much as I can in my projects so thought I should give out a suggestion incase you wanted something similar as well.

**Comment by DylanB5402** [comment]
That's super handy to know, thanks!
